---
- name: Configure open ports with firewalld.
  firewalld:
    state: "{{ item.state }}"
    port: "{{ item.port }}"
    zone: "{{ firewalld_default_interface_zone }}"
    immediate: true
    permanent: true
  with_items:
    - {state: 'enabled', port: '22/tcp'}

- name: Set default interface to external
  ansible.posix.firewalld:
    interface: "{{ ansible_default_ipv4.interface }}"
    zone: "{{ firewalld_default_interface_zone }}"
    permanent: true
    immediate: true
    state: enabled

- name: Disable AllowZoneDrifting in firewalld config
  lineinfile:
    dest: /etc/firewalld/firewalld.conf
    regexp: '^AllowZoneDrifting'
    line: 'AllowZoneDrifting=no'
    state: present

- name: Restart firewalld
  tags: molecule-idempotence-notest
  command: firewall-cmd --reload
